local addonName, addon = ...

local L = LibStub("AceLocale-3.0"):GetLocale(addonName) 

local sources = addon.Enum.Sources
local zones = addon.Enum.Zones

local manuscripts = {
    {
        name = "Cliffside Wylderdrake: Black Hair",
        itemID = 196986,
        questID = 69186,
        source = sources.Rare,
        rareNames = {
            L["Blightpaw the Depraved"],
            L["High Shaman Rotknuckle"],
            L["Blightfur"],
        },
    },
    {
        name = "Cliffside Wylderdrake: Spiked Back",
        itemID = 196970,
        questID = 69170,
        source = sources.Rare,
        rareName = L["Gethdazr"],
    },
    {
        name = "Cliffside Wylderdrake: Maned Jaw",
        itemID = 196983,
        questID = 69183,
        source = sources.Rare,
        rareNames = {
            L["Corrupted Proto-Dragon"],
            L["Diluu"],
        },
    },
    {
        name = "Cliffside Wylderdrake: Short Horns",
        itemID = 196994,
        questID = 69194,
        source = sources.Rare,
        rareName = L["Treasure-Mad Trambladd"],
    },
    {
        name = "Cliffside Wylderdrake: Swept Horns",
        itemID = 196999,
        questID = 69199,
        source = sources.Rare,
        rareNames = {
            L["Shadeslash Trakken"],
            L["Tikarr Frostclaw"],
            L["Sparkspitter Vrak"],
        },
    },
    {
        name = "Cliffside Wylderdrake: Narrow Stripes Pattern",
        itemID = 197008,
        questID = 69208,
        source = sources.Rare,
        rareNames = {
            L["Phleep"],
            L["Sandana the Tempest"],
            L["Innumerable Ruination"],
            L["Lord Epochbrgl"],
        },
    },
    {
        name = "Cliffside Wylderdrake: Maned Tail",
        itemID = 197016,
        questID = 69216,
        source = sources.Rare,
        rareZone = zones.ohn,
    },
    {
        name = "Cliffside Wylderdrake: Heavy Horns",
        itemID = 196992,
        questID = 69192,
        source = sources.Rare,
        rareNames = {
            L["Researcher Sneakwing"],	
            L["Razk'vex the Untamed"],
            L["Ancient Hornswog"],
            L["Acrosoth"],
            L["Tomnu"],
            L["Nulltheria the Void Gazer"],
        },
    },
    {
        name = "Cliffside Wylderdrake: Black Horns",
        itemID = 196991,
        questID = 69191,
        source = sources.Hunt,
    },
    {
        name = "Cliffside Wylderdrake: Black Scales",
        itemID = 197013,
        questID = 69213,
        source = sources.Reputation,
        reputations = {
            2517,
            2518,
        },
        friendshipRank = L["True Friend"],
        itemCost = {
            {
                itemID = 190316,
                quantity = 1,
            },
        },
        currencyCost = {
            {
                currencyID = 2003,
                quantity = 400,
            },
        },
    },
    {
        name = "Cliffside Wylderdrake: Dark Skin Variation",
        itemID = 197015,
        questID = 69215,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 9,
    },
    {
        name = "Cliffside Wylderdrake: Gold and Orange Armor",
        itemID = 196966,
        questID = 69166,
        source = sources.DragonRacingAchievement,
        achievementID = 15937,
    },
    {
        name = "Cliffside Wylderdrake: Triple Head Horns",
        itemID = 196980,
        questID = 69180,
        source = sources.Inscription,
        spellID = 383576,
        recipeID = 198893,
    },
    {
        name = "Cliffside Wylderdrake: Gold and Black Armor",
        itemID = 196964,
        questID = 69164,
        source = sources.Reputation,
        reputations = {
            2517,
            2518,
        },
        friendshipRank = L["Friend"],
    },
    {
        name = "Cliffside Wylderdrake: Branched Horns",
        itemID = 196996,
        questID = 69196,
        source = sources.Rare,
        rareName = L["Shade of Grief"],
    },
    {
        name = "Cliffside Wylderdrake: Head Fin",
        itemID = 196975,
        questID = 69175,
        source = sources.Dungeon,
        bossName = L["Primal Tsunami"],
        zoneID = 14082,
    },
    {
        name = "Cliffside Wylderdrake: Dual Horned Chin",
        itemID = 196973,
        questID = 69173,
        source = sources.Rare,
        rareNames = {
            L["Blightpaw the Depraved"],
            L["High Shaman Rotknuckle"],
            L["Blightfur"],
        },
    },
    {
        name = "Cliffside Wylderdrake: Maned Neck",
        itemID = 197023,
        questID = 69223,
        source = sources.Rare,
        rareNames = {
            L["Klozicc the Ascended"],
            L["Beogoka"],
            L["Notfar the Unbearable"],
            L["Graniteclaw"],
        },
    },
    {
        name = "Cliffside Wylderdrake: Silver and Purple Armor",
        itemID = 196962,
        questID = 69162,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 26,
    },
    {
        name = "Cliffside Wylderdrake: Conical Head",
        itemID = 196981,
        questID = 69181,
        source = sources.Inscription,
        spellID = 383574,
        recipeID = 198891,
    },
    {
        name = "Cliffside Wylderdrake: Silver and Blue Armor",
        itemID = 196963,
        questID = 69163,
        source = sources.Inscription,
        spellID = 391836,
        recipeID = 201734,
    },
    {
        name = "Cliffside Wylderdrake: Finned Neck",
        itemID = 197022,
        questID = 69222,
        source = sources.Rare,
        rareNames = {
            L["O'nank Shorescour"],
            L["Brackle"],
            L["Gorjo the Crab Shackler"],
            L["Skewersnout"],
            L["Swog'ranka"],
            L["Massive Magmashell"],
            L["Lord Epochbrgl"],
        },
    },
    {
        name = "Cliffside Wylderdrake: Spiked Horns",
        itemID = 196995,
        questID = 69195,
        source = sources.Reputation,
        reputation = 2526,
        reputationRank = 7,
    },
    {
        name = "Cliffside Wylderdrake: Red Hair",
        itemID = 196988,
        questID = 69188,
        source = sources.Inscription,
        spellID = 383575,
        recipeID = 198892,
    },
    {
        name = "Cliffside Wylderdrake: Red Scales",
        itemID = 197010,
        questID = 69210,
        source = sources.Renown,
        renownFaction = 2507,
        renownRank = 22,
    },
    {
        name = "Cliffside Wylderdrake: Coiled Horns",
        itemID = 197000,
        questID = 69200,
        source = sources.Rare,
        rareName = L["Loot Specialist"],
    },
    {
        name = "Cliffside Wylderdrake: Horned Jaw",
        itemID = 196985,
        questID = 69185,
        source = sources.Rare,
        rareNames = {
            L["Fisherman Tinnak"],
            L["Shade of Grief"],
            L["Nulltheria the Void Gazer"],
            L["Blightfur"],
            L["Forgotten Gryphon"],
        },
    },
    {
        name = "Cliffside Wylderdrake: Ears",
        itemID = 196982,
        questID = 69182,
        source = sources.Rare,
        rareNames = {
            L["Sharpfang"],
            L["Mange the Outcast"],
            L["Snarglebone"],
            L["Blightpaw the Depraved"],
            L["Scav Notail"],
            L["High Shaman Rotknuckle"],
            L["Blightfur"],
        },
    },
    {
        name = "Cliffside Wylderdrake: Flared Cheek",
        itemID = 197002,
        questID = 69202,
        source = sources.DragonRacingContainer,
        containerID = 204359,
    },
    {
        name = "Cliffside Wylderdrake: Spiked Legs",
        itemID = 197004,
        questID = 69204,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 15,
    },
    {
        name = "Cliffside Wylderdrake: Steel and Yellow Armor",
        itemID = 196968,
        questID = 69168,
        source = sources.Inscription,
    },
    {
        name = "Cliffside Wylderdrake: Split Head Horns",
        itemID = 196977,
        questID = 69177,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 9,
    },
    {
        name = "Cliffside Wylderdrake: Wide Stripes Pattern",
        itemID = 197007,
        questID = 69207,
        source = sources.Dungeon,
        bossName = L["Primal Tsunami"],
        zoneID = 14082,
    },
    {
        name = "Cliffside Wylderdrake: Scaled Pattern",
        itemID = 197009,
        questID = 69209,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 15,
    },
    {
        name = "Cliffside Wylderdrake: Plated Nose",
        itemID = 197006,
        questID = 69206,
        source = sources.Reputation,
        reputation = 2526,
        reputationRank = 6,
    },
    {
        name = "Cliffside Wylderdrake: Curled Head Horns",
        itemID = 196979,
        questID = 69179,
        source = sources.DragonRacingContainer,
        containerID = 199192,
    },
    {
        name = "Cliffside Wylderdrake: Finned Tail",
        itemID = 197018,
        questID = 69218,
        source = sources.Reputation,
        reputation = 2550,
        friendshipRank = L["High"],
    },
    {
        name = "Cliffside Wylderdrake: Spiked Cheek",
        itemID = 197003,
        questID = 69203,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 9,
    },
    {
        name = "Cliffside Wylderdrake: Head Mane",
        itemID = 196976,
        questID = 69176,
        source = sources.Rare,
    },
    {
        name = "Cliffside Wylderdrake: Blue Scales",
        itemID = 197012,
        questID = 69212,
        source = sources.Renown,
        renownFaction = 2511,
        renownRank = 19,
    },
    {
        name = "Cliffside Wylderdrake: Blonde Hair",
        itemID = 196987,
        questID = 69187,
        source = sources.DragonRacingAchievement,
        achievementID = 15926,
    },
    {
        name = "Cliffside Wylderdrake: Hook Horns",
        itemID = 196998,
        questID = 69198,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 15,
    },
    {
        name = "Cliffside Wylderdrake: Spiked Brow",
        itemID = 196971,
        questID = 69171,
        source = sources.DragonRacingContainer,
        containerID = 199192, 
    },
    {
        name = "Cliffside Wylderdrake: White Hair",
        itemID = 196989,
        questID = 69189,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 15, 
    },
    {
        name = "Cliffside Wylderdrake: Spear Tail",
        itemID = 197020,
        questID = 69220,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 15, 
    },
    {
        name = "Cliffside Wylderdrake: Finned Jaw",
        itemID = 196984,
        questID = 69184,
        --source = sources., 
    },
    {
        name = "Cliffside Wylderdrake: Blunt Spiked Tail",
        itemID = 197019,
        questID = 69219,
        source = sources.Rare,
        rareZone = zones.ws, 
    },
    {
        name = "Cliffside Wylderdrake: Finned Back",
        itemID = 196969,
        questID = 69169,
        source = sources.Reputation,
        reputation = 2550,
        friendshipRank = L["Low"], 
    },
    {
        name = "Cliffside Wylderdrake: Large Tail Spikes",
        itemID = 197017,
        questID = 69217,
        source = sources.DragonRacingContainer,
        containerID = 199192, 
    },
    {
        name = "Cliffside Wylderdrake: Sleek Horns",
        itemID = 196993,
        questID = 69193,
        --source = sources., 
    },
    {
        name = "Cliffside Wylderdrake: Horned Nose",
        itemID = 197005,
        questID = 69205,
        source = sources.Rare,
        rareNames = {
            L["Dragonhunter Igordan"],	
            L["Rohzor Forgesmash"],
            L["Cauldronbearer Blakor"],
            L["Rasnar the War Ender"],	
            L["Harkyn Grymstone"],		
            L["Dragonhunter Gorund"],	
            L["Captain Lancer"],
        }, 
    },
    {
        name = "Cliffside Wylderdrake: Finned Cheek",
        itemID = 197001,
        questID = 69201,
        source = sources.Rare,
        rareNames = {
            L["Anhydros the Tidetaker"],
            L["Gushgut the Beaksinker"],
            L["Fisherman Tinnak"],
            L["Cascade"],	
            L["Snufflegust"],
            L["Astray Splasher"],
            L["Seereel, the Spring"],	
            L["Spellwrought Snowman"],
        }, 
    },
    {
        name = "Cliffside Wylderdrake: Four-Horned Chin",
        itemID = 196974,
        questID = 69174,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 15, 
    },
    {
        name = "Cliffside Wylderdrake: Green Scales",
        itemID = 197011,
        questID = 69211,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = 19, 
    },
    {
        name = "Cliffside Wylderdrake: Plated Brow",
        itemID = 196972,
        questID = 69172,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 9, 
    },
    --{
    --    name = "Cliffside Wylderdrake: Helm",
    --    itemID = 196990,
    --    questID = 69190,
    --},
    {
        name = "Cliffside Wylderdrake: Armor",
        itemID = 196961,
        questID = 69161,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 26,
    }    
}

for k, v in pairs(manuscripts) do
    v.category = addon.Enum.Drakes.CliffsideWylderdrake
    table.insert(addon.db, v)
end
