local addonName, addon = ...

local L = LibStub("AceLocale-3.0"):GetLocale(addonName)
local sources = addon.Enum.Sources

addon.DirigibleDB = {
    {
        itemID = 225542,
        questID = 83308,
        name = "Delver's Dirigible Schematic: Void",
        source = sources.Other,
        otherDescription = "Zekvir T??",
        category = 1,
    },
	{
        itemID = 224771,
        questID = 82181,
        name = "Delver's Dirigible Schematic: Empennage",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
	{
        itemID = 224960,
        questID = 82176,
        name =  "Delver's Dirigible Schematic: Lantern Wing",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 1,
    },
	{
        itemID = 224769,
        questID = 82183,
        name = "Delver's Dirigible Schematic: Rotor Blades",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
	{
        itemID = 224979,
        questID = 82185,
        name = "Delver's Dirigible Schematic: Zeppelin",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 1,
    },
	{
        itemID = 224768,
        questID = 82171,
        name = "Delver's Dirigible Schematic: Wing-Mounted Propeller",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
	{
        itemID = 224770,
        questID = 82167,
        name = "Delver's Dirigible Schematic: Front-Mounted Propeller",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
	{
        itemID = 224982,
        questID = 82179,
        name = "Delver's Dirigible Schematic: Exhaust",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 1,
    },
	{
        itemID = 224981,
        questID = 82187,
        name = "Delver's Dirigible Schematic: Brown Paint",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 1,
    },
	{
        itemID = 224980,
        questID = 82170,
        name = "Delver's Dirigible Schematic: Front-Mounted Lantern",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 1,
    },

	{
        itemID = 235687,
        questID = 82180,
        name = "Delver's Dirigible Schematic: Spoiler",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
    {
        itemID = 235686,
        questID = 82190,
        name = "Delver's Dirigible Schematic: White Paint",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
    {
        itemID = 235685,
        questID = 82168,
        name = "Delver's Dirigible Schematic: Drill",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
    {
        itemID = 235684,
        questID = 82182,
        name = "Delver's Dirigible Schematic: Glider",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
    {
        itemID = 235683,
        questID = 82173,
        name = "Delver's Dirigible Schematic: Turbine",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
    {
        itemID = 235695,
        questID = 82189,
        name = "Delver's Dirigible Schematic: Red Paint",
        category = 1,
    },
    {
        itemID = 238837,
        questID = 86198,
        name = "Delver's Dirigible Schematic: Pale Paint",
        source = sources.Renown,
        renownFaction = 2688,
        renownRank = 8,
        category = 1,
    },
    {
        itemID = 238839,
        questID = 86199,
        name = "Delver's Dirigible Schematic: Arathi Decal",
        source = sources.Renown,
        renownFaction = 2688,
        renownRank = 8,
        category = 1,
    },
    {
        itemID = 235698,
        questID = 82194,
        name = "Delver's Dirigible Schematic: Horde Decal",
        category = 1,
    },
    {
        itemID = 235697,
        questID = 82192,
        name = "Delver's Dirigible Schematic: Alliance Decal",
        category = 1,
    },
    {
        itemID = 235694,
        questID = 82117,
        name = "Delver's Dirigible Schematic: Blue Paint",
        category = 1,
    },
    {
        itemID = 235693,
        questID = 82175,
        name = "Delver's Dirigible Schematic: Rocket",
        category = 1,
    },
    
    -- Gob-trotter schematics
	{
        itemID = 233196,
        questID = 86296,
        name =  "Delver's Gob-Trotter Schematic: Gold",
        source = sources.Achievement,
        achievementID = 41210,
        category = 2,
    },
	{
        itemID = 230217,
        questID = 85177,
        name =  "Delver's Gob-Trotter Schematic: Flamethrower",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 2,
    },
    {
        itemID = 230216,
        questID = 85175,
        name =  "Delver's Gob-Trotter Schematic: Harpoon",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 2,
    },
    {
        itemID = 230219,
        questID = 85181,
        name =  "Delver's Gob-Trotter Schematic: Balloon",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 2,
    },
    {
        itemID = 230218,
        questID = 85179,
        name =  "Delver's Gob-Trotter Schematic: Pipes",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 2,
    },
    {
        itemID = 230220,
        questID = 85183,
        name =  "Delver's Gob-Trotter Schematic: Green",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 2,
    },


    -- These five were in the game files but were added to the vendor in 11.2
    {
        itemID = 235692,
        questID = 82177,
        name = "Delver's Dirigible Schematic: Thrusters",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
    {
        itemID = 235691,
        questID = 82191,
        name = "Delver's Dirigible Schematic: Yellow Paint",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
    {
        itemID = 235690,
        questID = 82169,
        name = "Delver's Dirigible Schematic: Harpoon",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
    {
        itemID = 235689,
        questID = 82186,
        name = "Delver's Dirigible Schematic: Kite",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
    {
        itemID = 235688,
        questID = 82174,
        name = "Delver's Dirigible Schematic: Fan",
        source = sources.Vendor,
        vendorName = L["Sir Finley"],
        zoneID = 14771,
        category = 1,
    },
    
    -- This one already existed in 11.1 but finally had a source added in 11.2, the rest were new in 11.2
    {
        itemID = 235696,
        questID = 82193,
        name = "Delver's Dirigible Schematic: Explorer Decal",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 1,
    },
    
    -- Mana-skimmer schematics
    {
        itemID = 238178,
        questID = 88814,
        name =  "Delver's Mana-Skimmer Schematic: Canister",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 3,
    },
    {
        itemID = 238181,
        questID = 88820,
        name =  "Delver's Mana-Skimmer Schematic: Energy Thrusters",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 3,
    },
    {
        itemID = 238177,
        questID = 88816,
        name =  "Delver's Mana-Skimmer Schematic: Emitter",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 3,
    },
    {
        itemID = 238179,
        questID = 88815,
        name =  "Delver's Mana-Skimmer Schematic: Quad Glider",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 3,
    },
    {
        itemID = 238180,
        questID = 88817,
        name =  "Delver's Mana-Skimmer Schematic: Void Paint",
        source = sources.Vendor,
        vendorName = L["Reno Jackson"],
        zoneID = 14771,
        category = 3,
    },
    {
        itemID = 238182,
        questID = 88819,
        name = "Delver's Mana-Skimmer Schematic: Hyperdrive",
        source = sources.Other,
        otherDescription = "Ky'veza T??",
        category = 3,
    },
}