local addonName, addon = ...

local L = LibStub("AceLocale-3.0"):GetLocale(addonName) 

local sources = addon.Enum.Sources
local zones = addon.Enum.Zones

local manuscripts = {
    {
        name = "Renewed Proto-Drake: Beaked Snout",
        itemID = 197401,
        questID = 69602,
        source = sources.Dungeon,
        bossName = L["Erkhart Stormvein"],
        zoneID = 14063,
    },
    {
        name = "Renewed Proto-Drake: Heavy Scales",
        itemID = 197397,
        questID = 69598,
        source = sources.Dungeon,
        bossName = L["Warlord Sargha"],
        zoneID = 14011,
    },
    {
        name = "Renewed Proto-Drake: Ears",
        itemID = 197376,
        questID = 69577,
        source = sources.Dungeon,
        bossName = L["Warlord Sargha"],
        zoneID = 14011,
    },
    {
        name = "Renewed Proto-Drake: Skyterror Pattern",
        itemID = 197396,
        questID = 69597,
        source = sources.Dungeon,
        bossName = L["Decatriarch Wratheye"],
        zoneID = 13991,
    },
    {
        name = "Renewed Proto-Drake: Finned Tail",
        itemID = 197404,
        questID = 69605,
        source = sources.Rare,
        rareName = L["Blightfur"],
    },
    {
        name = "Renewed Proto-Drake: Club Tail",
        itemID = 197403,
        questID = 69604,
        source = sources.Rare,
        rareNames = {
            L["Researcher Sneakwing"],
            L["Ancient Hornswog"],
            L["Razk'vex the Untamed"],
            L["Acrosoth"],
            L["Tomnu"],
            L["Nulltheria the Void Gazer"],
        },
    },
    {
        name = "Renewed Proto-Drake: Heavy Horns",
        itemID = 197383,
        questID = 69584,
        source = sources.Rare,
        rareNames = {
            L["Elemental Storms"],
        },
    },
    {
        name = "Renewed Proto-Drake: White Horns",
        itemID = 197382,
        questID = 69583,
        source = sources.Rare,
        rareNames = {
            L["Fisherman Tinnak"],
            L["Shade of Grief"],
            L["Blightfur"],
            L["Nulltheria the Void Gazer"],
            L["Forgotten Gryphon"],
        },
    },
    {
        name = "Renewed Proto-Drake: Impaler Horns",
        itemID = 197379,
        questID = 69580,
        source = sources.Rare,
        rareNames = {
            L["Firava the Rekindler"],
            L["Summoned Destroyer"],
            L["Bisquius"],
            L["Qalashi War Mammoth"],
            L["Magmaton"],
            L["Battlehorn Pyrhus"],
            L["Lookout Mordren"],
            L["Worldcarver A'tir"],
            L["Moskhoi"],
            L["Smogswog the Firebreather"],
            L["Death's Shadow"],
            L["Gamgus"],
            L["Massive Magmashell"],
            L["Innumerable Ruination"],
            L["Galnmor"],
            L["Infernum"],
            L["Kain Firebrand"],
        },
    },
    {
        name = "Renewed Proto-Drake: Purple Hair",
        itemID = 197372,
        questID = 69573,
        source = sources.Rare,
        rareNames = {
            L["Sandana the Tempest"],
            L["Zenet Avis"],
            L["Prozela Galeshot"],
            L["Ty'foon the Ascended"],
            L["Terillod the Devout"],
            L["Sparkspitter Vrak"],
            L["Mikrin of the Raging Winds"],
            L["Tempestrian"],
            L["Gaelzion"],
            L["Pipspark Thundersnap"],
            L["Karantun"],
            L["Voraazka"],
        },
    },
    {
        name = "Renewed Proto-Drake: Gray Hair",
        itemID = 197367,
        questID = 69568,
        source = sources.Rare,
        rareZone = zones.ohn,
    },
    {
        name = "Renewed Proto-Drake: Shark Snout",
        itemID = 197400,
        questID = 69601,
        source = sources.Rare,
        rareNames = {
            L["Liskheszaera"],
            L["Trilvarus Loreweaver"],
            L["Grand Artificer Zeerak"],
            L["Motivator Krathos"],
            L["Srivantor"],
        },
    },
    {
        name = "Renewed Proto-Drake: Snub Snout",
        itemID = 197398,
        questID = 69599,
        source = sources.Rare,
        rareNames = {
            L["Gnarls"],
            L["Azra's Prized Peony"],
            L["Morlash"],
        },
    },
    {
        name = "Renewed Proto-Drake: Armor",
        itemID = 197357,
        questID = 69558,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 26,
    },
    --{
    --    name = "Renewed Proto-Drake: Helm",
    --    itemID = 197373,
    --    questID = 69574,
    --},
    {
        name = "Renewed Proto-Drake: Hairy Back",
        itemID = 197356,
        questID = 69557,
    },
    {
        name = "Renewed Proto-Drake: Horned Back",
        itemID = 197354,
        questID = 69555,
    },
    {
        name = "Renewed Proto-Drake: Embodiment of the Storm-Eater",
        itemID = 201790,
        questID = 72367,
        source = sources.Raid,
        bossName = L["Raszageth the Storm-Eater"],
    },
    {
        name = "Renewed Proto-Drake: Antlers",
        itemID = 202278,
        questID = 73058,
        source = sources.Chest,
        chestName = L["Obsidian Grand Cache"],
    },
    {
        name = "Renewed Proto-Drake: Predator Pattern",
        itemID = 197394,
        questID = 69595,
        source = sources.Inscription,
        spellID = 383580,
        recipeID = 198899,
    },
    {
        name = "Renewed Proto-Drake: Silver and Blue Armor",
        itemID = 197347,
        questID = 69548,
        source = sources.Inscription,
        spellID = 383586,
        recipeID = 201742,
    },
    {
        name = "Renewed Proto-Drake: Spined Crest",
        itemID = 197362,
        questID = 69563,
        source = sources.Inscription,
        spellID = 383582,
        recipeID = 198901,
    },
    {
        name = "Renewed Proto-Drake: Bovine Horns",
        itemID = 197377,
        questID = 69578,
        source = sources.Inscription,
        spellID = 383581,
        recipeID = 201741,
    },
    {
        name = "Renewed Proto-Drake: Gold and Black Armor",
        itemID = 197346,
        questID = 69547,
        source = sources.Reputation,
        reputations = {
            2517,
            2518,
        },
        friendshipRank = L["Friend"],
    },
    {
        name = "Renewed Proto-Drake: Razor Snout",
        itemID = 197399,
        questID = 69600,
        source = sources.Quest,
        sourceQuestID = 66831,
    },
    {
        name = "Renewed Proto-Drake: Gold and Red Armor",
        itemID = 197351,
        questID = 69552,
        source = sources.DragonRacingAchievement,
        achievementID = 15928,
    },
    {
        name = "Renewed Proto-Drake: Blue Hair",
        itemID = 197368,
        questID = 69569,
        source = sources.Reputation,
        reputation = 2550,
        friendshipRank = L["Maximum"],
    },
    {
        name = "Renewed Proto-Drake: Black Scales",
        itemID = 197392,
        questID = 69593,
        source = sources.Reputation,
        reputations = {
            2517,
            2518,
        },
        friendshipRank = L["Friend"],
    },
    {
        name = "Renewed Proto-Drake: Steel and Yellow Armor",
        itemID = 197352,
        questID = 69553,
        source = sources.Inscription,
        spellID = 383587,
        recipeID = 201738,
    },
    {
        name = "Renewed Proto-Drake: Malevolent Horns",
        itemID = 202279,
        questID = 73056,
        source = sources.Reputation,
        reputation = 2526,
        reputationRank = 7,
    },
    {
        name = "Renewed Proto-Drake: Spined Brow",
        itemID = 197360,
        questID = 69561,
        source = sources.Renown,
        renownFaction = 2507,
        renownRank = 9,
    },
    {
        name = "Renewed Proto-Drake: Silver and Purple Armor",
        itemID = 197350,
        questID = 69551,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 26,
    },
    {
        name = "Renewed Proto-Drake: Spiked Club Tail",
        itemID = 197402,
        questID = 69603,
        source = sources.Renown,
        renownFaction = 2507,
        renownRank = 15,
    },
    {
        name = "Renewed Proto-Drake: Maned Crest",
        itemID = 197363,
        questID = 69564,
        source = sources.Renown,
        renownFaction = 2507,
        renownRank = 9,
    },
    {
        name = "Renewed Proto-Drake: Harrier Pattern",
        itemID = 197395,
        questID = 69596,
        source = sources.Renown,
        renownFaction = 2507,
        renownRank = 15,
    },
    {
        name = "Renewed Proto-Drake: Gradient Horns",
        itemID = 197381,
        questID = 69582,
        source = sources.Quest,
        sourceQuestID = 66187,
    },
    {
        name = "Renewed Proto-Drake: Spiked Jaw",
        itemID = 197386,
        questID = 69587,
        source = sources.Renown,
        renownFaction = 2507,
        renownRank = 9,
    },
    {
        name = "Renewed Proto-Drake: Thick Spined Jaw",
        itemID = 197355,
        questID = 69585,
        source = sources.Reputation,
        reputation = 2550,
        friendshipRank = L["Low"],
    },
    {
        name = "Renewed Proto-Drake: Swept Horns",
        itemID = 197374,
        questID = 69575,
        source = sources.Renown,
        renownFaction = 2507,
        renownRank = 15,
    },
    {
        name = "Renewed Proto-Drake: Green Scales",
        itemID = 197389,
        questID = 66720,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = 19,
    },
    {
        name = "Renewed Proto-Drake: Stubby Snout",
        itemID = 202273,
        questID = 73054,
        source = sources.Reputation,
        reputation = 2526,
        reputationRank = 6,
    },
    {
        name = "Renewed Proto-Drake: Plated Brow",
        itemID = 202274,
        questID = 73055,
        source = sources.DragonRacingContainer,
        containerID = 204359,
    },
    {
        name = "Renewed Proto-Drake: Blue Scales",
        itemID = 197390,
        questID = 69591,
        source = sources.Renown,
        renownFaction = 2511,
        renownRank = 19,
    },
    {
        name = "Renewed Proto-Drake: Bronze Scales",
        itemID = 197391,
        questID = 69592,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 21,
    },
    {
        name = "Renewed Proto-Drake: Red Hair",
        itemID = 197370,
        questID = 69571,
        source = sources.DragonRacingAchievement,
        achievementID = 15916,
    },
    {
        name = "Renewed Proto-Drake: Curved Spiked Brow",
        itemID = 197358,
        questID = 69559,
        source = sources.Renown,
        renownFaction = 2507,
        renownRank = 15,
    },
    {
        name = "Renewed Proto-Drake: Dual Horned Crest",
        itemID = 197366,
        questID = 69567,
        source = sources.DragonRacingContainer,
        containerID = 199192,
    },
    {
        name = "Renewed Proto-Drake: Spiked Crest",
        itemID = 197361,
        questID = 69562,
        source = sources.Quest,
        sourceQuestID = 70134,
    },
    {
        name = "Renewed Proto-Drake: Thin Spined Jaw",
        itemID = 197387,
        questID = 69588,
        source = sources.DragonRacingContainer,
        containerID = 199192,
    },
    {
        name = "Renewed Proto-Drake: Hairy Brow",
        itemID = 197359,
        questID = 69560,
        source = sources.Quest,
        sourceQuestID = 66658,
    },
    {
        name = "Renewed Proto-Drake: Curved Horns",
        itemID = 197380,
        questID = 69581,
        source = sources.Quest,
        sourceQuestID = 68797,
    },
    {
        name = "Renewed Proto-Drake: Spined Tail",
        itemID = 197406,
        questID = 69607,
        source = sources.Quest,
        sourceQuestID = 70061,
    },
    {
        name = "Renewed Proto-Drake: Spiked Throat",
        itemID = 197407,
        questID = 69608,
        source = sources.Quest,
        sourceQuestID = 66700,
    },
    {
        name = "Renewed Proto-Drake: Horned Jaw",
        itemID = 197385,
        questID = 69586,
        source = sources.Quest,
        sourceQuestID = 66270,
    },
    {
        name = "Renewed Proto-Drake: Subtle Horns",
        itemID = 197378,
        questID = 69579,
        source = sources.Quest,
        sourceQuestID = 66124,
    },
    {
        name = "Renewed Proto-Drake: Finned Jaw",
        itemID = 197388,
        questID = 69589,
        source = sources.Quest,
        sourceQuestID = 65867,
    },
    {
        name = "Renewed Proto-Drake: Curled Horns",
        itemID = 197375,
        questID = 69576,
        source = sources.Quest,
        sourceQuestID = 66783,
    },
    {
        name = "Renewed Proto-Drake: Finned Throat",
        itemID = 197408,
        questID = 69609,
        source = sources.Quest,
        sourceQuestID = 65845,
    },
    {
        name = "Renewed Proto-Drake: Maned Tail",
        itemID = 197405,
        questID = 69606,
        source = sources.Quest,
        sourceQuestID = 66024,
    },
    {
        name = "Renewed Proto-Drake: Finned Crest",
        itemID = 197365,
        questID = 69566,
        source = sources.Quest,
        sourceQuestID = 68797,
    },
}

for k, v in pairs(manuscripts) do
    v.category = addon.Enum.Drakes.RenewedProtoDrake
    table.insert(addon.db, v)
end
