local addonName, addon = ...

local L = LibStub("AceLocale-3.0"):GetLocale(addonName)
local sources = addon.Enum.Sources

addon.ShapeshiftDB = {
	{
		itemID = 210645,
		questID = 78479,
		name = "Feather of Friends",
        source = sources.Quest,
        sourceQuestID = 78066,
	},
	{
		itemID = 210754,
		questID = 78527,
		name = "Feather of the Blazing Somnowl",
        source = sources.Raid,
        bossName = L["Fyrakk"],
	},
	{
		itemID = 211280,
		questID = 78525,
		name = "Feather of the Smoke Red Moon",
        source = sources.Raid,
        bossName = L["Tindral Sageswift"]
	},
	{
		itemID = 210735,
		questID = 78523,
		name = "Mark of the Auric Dreamstag",
        source = sources.Inscription,
	},
	{
		itemID = 211081,
		questID = 78514,
		name = "Mark of the Auroral Dreamtalon",
        source = sources.Chest,
        chestName = L["Dreamseed Cache"],
        zoneID = 14529,
	},
	{
		itemID = 211080,
		questID = 78512,
		name = "Mark of the Boreal Dreamtalon",
        source = sources.Chest,
        chestName = L["Dreamseed Cache"],
        zoneID = 14529,
	},
	{
		itemID = 210683,
		questID = 78513,
		name = "Mark of the Dreamtalon Matriarch",
        source = sources.Rare,
        rareName = L["Matriarch Keevah"],
	},
	{
		itemID = 210669,
		questID = 78507,
		name = "Mark of the Evergreen Dreamsaber",
        source = sources.ZoneDrop,
        zoneID = 14529,
	},
	{
		itemID = 210751,
		questID = 78528,
		name = "Mark of the Hibernating Runebear",
        source = sources.Raid,
        bossName = L["Aurostor, the Hibernating"],
	},
	{
		itemID = 210650,
		questID = 78503,
		name = "Mark of the Keen-Eyed Dreamsaber",
        source = sources.Rare,
        rareName = L["Keen-eyed Cian"],
	},
	{
		itemID = 210738,
		questID = 78519,
		name = "Mark of the Loamy Umbraclaw",
        source = sources.ZoneDrop,
        zoneID = 14529,
	},
	{
		itemID = 210731,
		questID = 78522,
		name = "Mark of the Lush Dreamstag",
        source = sources.ZoneDrop,
        zoneID = 14529,
	},
	{
		itemID = 210674,
		questID = 78511,
		name = "Mark of the Sable Dreamtalon",
        source = sources.Rare,
        rareName = L["Ristar the Rabid"],
	},
	{
		itemID = 210535,
		questID = 78448,
		name = "Mark of the Slumbering Somnowl",
        source = sources.ZoneDrop,
        zoneID = 14529,
	},
	{
		itemID = 210736,
		questID = 78524,
		name = "Mark of the Smoldering Dreamstag",
        source = sources.Rare,
        rareName = L["Talthonei Ashwhisper"],
	},
	{
		itemID = 210739,
		questID = 78520,
		name = "Mark of the Snowy Umbraclaw",
        source = sources.Chest,
        chestName = L["Dreamseed Cache"],
        zoneID = 14529,
	},
	{
		itemID = 210684,
		questID = 78515,
		name = "Mark of the Thriving Dreamtalon",
        source = sources.ZoneDrop,
        zoneID = 14529,
	},
	{
		itemID = 210647,
		questID = 78481,
		name = "Mark of the Umbramane",
        source = sources.Rare,
        rareName = L["Mosa Umbramane"],
	},
	{
		itemID = 210729,
		questID = 78517,
		name = "Mark of the Verdant Bristlebruin",
        source = sources.Rare,
        rareName = L["Moragh the Slothful"],
	},
	{
		itemID = 210728,
		questID = 78521,
		name = "Moon-Blessed Claw",
        source = sources.Container,
        containerID = 210991,
	},
	{
		itemID = 210727,
		questID = 78518,
		name = "Pollenfused Bristlebruin Fur Sample",
        source = sources.Chest,
        chestName = L["Pollenfused Bristlebruin Fur Sample"],
	},
	{
		itemID = 210753,
		questID = 78516,
		name = "Scale of the Prismatic Whiskerfish",
        source = sources.ZoneDrop,
        zoneID = 14529,
	},
	{
		itemID = 187933,
		questID = 65058,
		name = "Mark of the Duskwing Raven",
        source = sources.Inscription,
	},
	{
		itemID = 187887,
		questID = 65048,
		name = "Mark of the Gloomstalker Dredbat",
        source = sources.Inscription,
	},
	{
		itemID = 187934,
		questID = 65061,
		name = "Mark of the Midnight Runestag",
        source = sources.Inscription,
	},
	{
		itemID = 187931,
		questID = 65059,
		name = "Mark of the Regal Dredbat",
        source = sources.Inscription,
	},
	{
		itemID = 187936,
		questID = 65062,
		name = "Mark of the Sable Ardenmoth",
        source = sources.Inscription,
	},
	{
		itemID = 187888,
		questID = 64987,
		name = "Mark of the Shimmering Ardenmoth",
        source = sources.Inscription,
	},
	{
		itemID = 187884,
		questID = 64986,
		name = "Mark of the Twilight Runestag",
        source = sources.Inscription,
	},
	{
		itemID = 89868,
		questID = 62677,
		name = "Mark of the Cheetah",
        source = sources.Inscription,
	},
	{
		itemID = 140630,
		questID = 62678,
		name = "Mark of the Doe",
        source = sources.Inscription,
	},
	{
		itemID = 162022,
		questID = 62674,
		name = "Mark of the Dolphin",
        source = sources.Inscription,
	},
	{
		itemID = 162029,
		questID = 62676,
		name = "Mark of the Humble Flyer",
        source = sources.Inscription,
	},
	{
		itemID = 40919,
		questID = 62673,
		name = "Mark of the Orca",
        source = sources.Inscription,
	},
	{
		itemID = 129021,
		questID = 62675,
		name = "Mark of the Sentinel",
        source = sources.Inscription,
	},
	{
		itemID = 162027,
		questID = 62672,
		name = "Mark of the Tideskipper",
        source = sources.Inscription,
	},
}
