local addonName, addon = ...

local L = LibStub("AceLocale-3.0"):GetLocale(addonName) 

local sources = addon.Enum.Sources
local zones = addon.Enum.Zones

local manuscripts = {
    {
        name = "Windborne Velocidrake: White Horns",
        itemID = 197609,
        questID = 69813,
        source = sources.Rare,
        rareName = L["Wyrmslayer Angvardi"],
    },
    {
        name = "Windborne Velocidrake: Gray Horns",
        itemID = 197608,
        questID = 69812,
        source = sources.Rare,
        rareNames = {
            L["Oshigol"],
            L["Spellforged Brute"],
            L["Magmaton"],
            L["O'nank Shorescour"],
            L["Mahg the Trampler"],
            L["Skag the Thrower"],
            L["Tenmod"],
            L["Honmor"],
        },
    },
    {
        name = "Windborne Velocidrake: Swept Horns",
        itemID = 197606,
        questID = 69810,
        source = sources.Rare,
        rareNames = {
            L["Zenet Avis"],
            L["Sandana the Tempest"],
            L["Prozela Galeshot"],
            L["Terillod the Devout"],
            L["Mikrin of the Raging Winds"],
            L["Ty'foon the Ascended"],
            L["Sparkspitter Vrak"],
            L["Tempestrian"],
            L["Voraazka"],
            L["Karantun"],
            L["Gaelzion"],
            L["Pipspark Thundersnap"],
        },            
    },
    {
        name = "Windborne Velocidrake: Cluster Horns",
        itemID = 197602,
        questID = 69806,
        source = sources.Rare,
        rareNames = {
            L["Elemental Storms"],
        },
    },
    {
        name = "Windborne Velocidrake: Wavy Horns",
        itemID = 197601,
        questID = 69805,
        source = sources.Dungeon,
        bossName = L["Erkhart Stormvein"],
        zoneID = 14063,
    },
    {
        name = "Windborne Velocidrake: Feathery Tail",
        itemID = 197625,
        questID = 69829,
        source = sources.Dungeon,
        bossName = L["Balakar Khan"],
        zoneID = 14478,
    },
    {
        name = "Windborne Velocidrake: Club Tail",
        itemID = 197624,
        questID = 69828,
        source = sources.Rare,
        rareNames = {
            L["Elemental Storms"],
        },
    },
    {
        name = "Windborne Velocidrake: Spiked Back",
        itemID = 197586,
        questID = 69790,
        source = sources.Rare,
        rareNames = {
            L["Disoriented Watcher"],
            L["Ancient Protector"],
            L["Forgotten Creation"],
            L["Broodweaver Araznae"],
            L["Gethdazr"],
            L["Seeker Teryx"],
            L["Phenran"],
            L["Unstable Arcanogolem"],
            L["Srivantor"],
        },
    },
    {
        name = "Windborne Velocidrake: Shrieker Pattern",
        itemID = 197636,
        questID = 69847,
        source = sources.Rare,
        rareName = L["Ookbeard"],
    },
    {
        name = "Windborne Velocidrake: Reaver Pattern",
        itemID = 197635,
        questID = 69846,
        source = sources.Dungeon,
        bossName = L["Balakar Khan"],
        zoneID = 14478,
    },
    {
        name = "Windborne Velocidrake: Heavy Scales",
        itemID = 197617,
        questID = 69821,
        source = sources.Rare,
        rareName = L["Volcanakk"],
    },
    {
        name = "Windborne Velocidrake: Plated Neck",
        itemID = 197628,
        questID = 69834,
        source = sources.Rare,
        rareName = L["Lady Shaz'ra"],
    },
    {
        name = "Windborne Velocidrake: Finned Ears",
        itemID = 197595,
        questID = 69799,
        source = sources.Rare,
        rareName = L["Blue Terror"],
    },
    {
        name = "Windborne Velocidrake: Small Head Fin",
        itemID = 197590,
        questID = 69794,
        source = sources.Rare,
        rareName = L["Pyrachniss"],
    },
    {
        name = "Windborne Velocidrake: Large Head Fin",
        itemID = 197589,
        questID = 69793,
        source = sources.Rare,
        rareNames = {
            L["O'nank Shorescour"],
            L["Brackle"],
            L["Gorjo the Crab Shackler"],
            L["Skewersnout"],
            L["Swog'ranka"],
            L["Massive Magmashell"],
            L["Lord Epochbrgl"],
        },
    },
    {
        name = "Windborne Velocidrake: Feathery Head",
        itemID = 197593,
        questID = 69797,
        source = sources.Rare,
        rareNames = {
            L["Shardwing"],
            L["Tempestrian"],
        },
    },
    {
        name = "Windborne Velocidrake: Curved Horns",
        itemID = 197603,
        questID = 69807,
        source = sources.Quest,
        sourceQuestID = 66009,
    },
    {
        name = "Windborne Velocidrake: Maned Back",
        itemID = 197585,
        questID = 69789,
        source = sources.Chest,
        chestName = L["Forgotten Dragon Treasure"],
    },
    {
        name = "Windborne Velocidrake: Exposed Finned Tail",
        itemID = 197621,
        questID = 69825,
    },
    {
        name = "Windborne Velocidrake: Exposed Finned Neck",
        itemID = 197626,
        questID = 69831,
        source = sources.Vendor,
        vendorName = L["Kraxxus"],
        zoneID = 14433,
    },
    {
        name = "Windborne Velocidrake: Gray Hair",
        itemID = 197598,
        questID = 69802,
        source = sources.Dungeon,
        chestName = L["Decatriarch Wratheye"],
        zoneID = 13991,
    },
    {
        name = "Windborne Velocidrake: Black Scales",
        itemID = 197611,
        questID = 69815,
        source = sources.Reputation,
        reputations = {
            2517,
            2518,
        },
        friendshipRank = L["True Friend"],
    },
    {
        name = "Windborne Velocidrake: Steel and Orange Armor",
        itemID = 197579,
        questID = 69783,
        source = sources.Inscription,
    },
    {
        name = "Windborne Velocidrake: Yellow Horns",
        itemID = 197610,
        questID = 69814,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = 6,
    },
    {
        name = "Windborne Velocidrake: Beaked Snout",
        itemID = 197620,
        questID = 69824,
        source = sources.Reputation,
        reputation = 2550,
        friendshipRank = L["Medium"],
    },
    {
        name = "Windborne Velocidrake: Silver and Blue Armor",
        itemID = 197578,
        questID = 69782,
        source = sources.Inscription,
    },
    {
        name = "Windborne Velocidrake: Black Fur",
        itemID = 197597,
        questID = 69801,
        source = sources.Inscription,
    },
    {
        name = "Windborne Velocidrake: Ox Horns",
        itemID = 197604,
        questID = 69808,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = 6,
    },
    {
        name = "Windborne Velocidrake: Red Scales",
        itemID = 197614,
        questID = 69818,
        source = sources.Renown,
        renownFaction = 2507,
        renownRank = 22,
    },
    {
        name = "Windborne Velocidrake: Windswept Pattern",
        itemID = 197634,
        questID = 69845,
        source = sources.Inscription,
    },
    {
        name = "Windborne Velocidrake: Horned Jaw",
        itemID = 197596,
        questID = 69800,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = 6,
    },
    {
        name = "Windborne Velocidrake: Feathered Neck",
        itemID = 197630,
        questID = 69836,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = 6,
    },
    {
        name = "Windborne Velocidrake: Spined Head",
        itemID = 197592,
        questID = 69796,
        source = sources.Inscription,
    },
    {
        name = "Windborne Velocidrake: Feathered Back",
        itemID = 197587,
        questID = 69791,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = 15,
    },
    {
        name = "Windborne Velocidrake: Gold and Red Armor",
        itemID = 197580,
        questID = 69784,
        source = sources.DragonRacingAchievement,
        achievementID = 15931,
    },
    {
        name = "Windborne Velocidrake: Blue Scales",
        itemID = 197612,
        questID = 69816,
        source = sources.Renown,
        renownFaction = 2511,
        renownRank = 19,
    },
    {
        name = "Windborne Velocidrake: Silver and Purple Armor",
        itemID = 197581,
        questID = 69785,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 26,
    },
    {
        name = "Windborne Velocidrake: Hooked Snout",
        itemID = 197619,
        questID = 69823,
        source = sources.DragonRacingContainer,
        containerID = 199192,
    },
    {
        name = "Windborne Velocidrake: Exposed Finned Back",
        itemID = 197583,
        questID = 69787,
        source = sources.Reputation,
        reputation = 2526,
        reputationRank = 6,
    },

    {
        name = "Windborne Velocidrake: Hairy Head",
        itemID = 197591,
        questID = 69795,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = 15,
    },
    {
        name = "Windborne Velocidrake: Spiked Neck",
        itemID = 197629,
        questID = 69835,
        source = sources.Reputation,
        reputation = 2526,
        reputationRank = 7,
    },
    {
        name = "Windborne Velocidrake: Split Horns",
        itemID = 197607,
        questID = 69811,
        source = sources.Quest,
        sourceQuestID = 66155,
    },
    {
        name = "Windborne Velocidrake: Small Ears",
        itemID = 197594,
        questID = 69798,
        source = sources.DragonRacingContainer,
        containerID = 204359,
    },
    {
        name = "Windborne Velocidrake: Finned Back",
        itemID = 197584,
        questID = 69788,
        source = sources.Vendor,
        vendorName = L["Meiz"],
        zoneID = 13646,
    },
    {
        name = "Windborne Velocidrake: Long Snout",
        itemID = 197618,
        questID = 69822,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = 15,
    },
    {
        name = "Windborne Velocidrake: Curled Horns",
        itemID = 197605,
        questID = 69809,
        source = sources.DragonRacingContainer,
        containerID = 199192,
    },
    {
        name = "Windborne Velocidrake: Armor",
        itemID = 197588,
        questID = 69792,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 26,
    },
    {
        name = "Windborne Velocidrake: Bronze Scales",
        itemID = 197613,
        questID = 69817,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = 21,
    },
    {
        name = "Windborne Velocidrake: Red Hair",
        itemID = 197599,
        questID = 69803,
        source = sources.DragonRacingAchievement,
        achievementID = 15919,
    },
    --{
    --    name = "Windborne Velocidrake: Helm",
    --    itemID = 197600,
    --    questID = 69804,
    --},
    {
        name = "Windborne Velocidrake: Spiked Tail",
        itemID = 197623,
        questID = 69827,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = 15,
    },
    {
        name = "Windborne Velocidrake: Finned Neck",
        itemID = 197627,
        questID = 69832,
        source = sources.Quest,
        sourceQuestID = 66556,
    },
    {
        name = "Windborne Velocidrake: Finned Tail",
        itemID = 197622,
        questID = 69826,
        source = sources.Quest,
        sourceQuestID = 65702,
    },
}

for k, v in pairs(manuscripts) do
    v.category = addon.Enum.Drakes.WindborneVelocidrake
    table.insert(addon.db, v)
end
