local addonName, addon = ...

local L = LibStub("AceLocale-3.0"):GetLocale(addonName) 

local sources = addon.Enum.Sources
local zones = addon.Enum.Zones

local manuscripts = {
    {
        name = "Winding Slitherdrake: Embodiment of the Obsidian Gladiator",
        itemID = 205865,
        questID = 75941,
        source = sources.PvPSeason,
        achievementID = 17740, -- Season 2
        unobtainable = true,
    },
    {
        name = "Winding Slitherdrake: Antler Horns",
        itemID = 203338,
        questID = 73829,
        source = sources.Rare,
        rareName = L["Subterrax"],
    },
    --{
    --    name = "Winding Slitherdrake: Armor",
    --    itemID = 203305,
    --    questID = 73793,
    --},
    {
        name = "Winding Slitherdrake: Blonde Hair",
        itemID = 203322,
        questID = 73810,
        source = sources.Vendor,
        vendorName = L["Maztha"],
        zoneID = 13862,
    },
    {
        name = "Winding Slitherdrake: Blue and Silver Armor",
        itemID = 203300,
        questID = 73788,
        source = sources.Inscription,
    },
    {
        name = "Winding Slitherdrake: Blue Scales",
        itemID = 203350,
        questID = 73841,
        source = sources.Renown,
        renownFaction = 2511,
        renownRank = "19",
    },
    {
        name = "Winding Slitherdrake: Bronze Scales",
        itemID = 203351,
        questID = 73842,
        source = sources.Renown,
        renownFaction = 2510,
        renownRank = "21",
    },
    {
        name = "Winding Slitherdrake: Brown Hair",
        itemID = 203323,
        questID = 73811,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 13,
    },
    {
        name = "Winding Slitherdrake: Cluster Chin Horn",
        itemID = 203312,
        questID = 73800,
        source = sources.Vendor,
        vendorName = L["Ponzo"],
        zoneID = 14022,
    },
    {
        name = "Winding Slitherdrake: Cluster Horns",
        itemID = 203331,
        questID = 73820,
        source = sources.Rare,
        rareName = L["Professor Gastrinax"],
    },
    {
        name = "Winding Slitherdrake: Curled Cheek Horn",
        itemID = 203321,
        questID = 73809,
        source = sources.Rare,
        rareName = L["Skornak"],
    },
    {
        name = "Winding Slitherdrake: Curled Horns",
        itemID = 203334,
        questID = 73824,
        source = sources.Rare,
        rareName = L["General Zskorro"],
    },
    {
        name = "Winding Slitherdrake: Curled Nose",
        itemID = 203346,
        questID = 73837,
        source = sources.Vendor,
        vendorName = L["Ponzo"],
        zoneID = 14022,
    },
    {
        name = "Winding Slitherdrake: Curved Chin Horn",
        itemID = 203314,
        questID = 73802,
        source = sources.Inscription,
    },
    {
        name = "Winding Slitherdrake: Curved Horns",
        itemID = 203335,
        questID = 73825,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 13,
    },
    {
        name = "Winding Slitherdrake: Curved Nose Horn",
        itemID = 203349,
        questID = 73840,
        source = sources.Vendor,
        vendorName = L["Maztha"],
        zoneID = 13862,
    },
    {
        name = "Winding Slitherdrake: Ears",
        itemID = 203320,
        questID = 73808,
        source = sources.Rare,
        rareName = L["Dinn"],
    },
    {
        name = "Winding Slitherdrake: Finned Tip Tail",
        itemID = 203361,
        questID = 73853,
        source = sources.DragonRacingContainer,
        containerID = 205226,
    },
    {
        name = "Winding Slitherdrake: Grand Chin Thorn",
        itemID = 203310,
        questID = 73798,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 5,
    },
    {
        name = "Winding Slitherdrake: Green and Bronze Armor",
        itemID = 203299,
        questID = 73787,
        source = sources.Fyrakk,
        fyrakkType = addon.Enum.Fyrakk.Chest,
    },
    {
        name = "Winding Slitherdrake: Green Scales",
        itemID = 203352,
        questID = 73843,
        source = sources.Renown,
        renownFaction = 2503,
        renownRank = "19",
    },
    {
        name = "Winding Slitherdrake: Hairy Brow",
        itemID = 203308,
        questID = 73796,
        source = sources.Vendor,
        vendorName = L["Ponzo"],
        zoneID = 14022,
    },
    {
        name = "Winding Slitherdrake: Hairy Crest",
        itemID = 203318,
        questID = 73806,
        source = sources.Rare,
        rareName = L["Spinmarrow"],
    },
    {
        name = "Winding Slitherdrake: Hairy Jaw",
        itemID = 203343,
        questID = 73834,
        source = sources.DragonRacingContainer,
        containerID = 210549,
    },
    {
        name = "Winding Slitherdrake: Hairy Tail",
        itemID = 203362,
        questID = 73854,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 16,
    },
    {
        name = "Winding Slitherdrake: Hairy Throat",
        itemID = 203365,
        questID = 73857,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 16,
    },
    {
        name = "Winding Slitherdrake: Heavy Scales",
        itemID = 205341,
        questID = 75743,
        source = sources.Rare,
        rareName = L["Kapraku"],
    },
    --{
    --    name = "Winding Slitherdrake: Helm",
    --    itemID = 203326,
    --    questID = 73814,
    --},
    {
        name = "Winding Slitherdrake: Impaler Horns",
        itemID = 203339,
        questID = 73830,
        source = sources.Rare,
        rareName = L["Magtembo"],
    },
    {
        name = "Winding Slitherdrake: Large Finned Crest",
        itemID = 203316,
        questID = 73804,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 5,
    },
    {
        name = "Winding Slitherdrake: Large Finned Tail",
        itemID = 203360,
        questID = 73852,
        source = sources.DragonRacingContainer,
        containerID = 210549,
    },
    {
        name = "Winding Slitherdrake: Large Finned Throat",
        itemID = 203363,
        questID = 73855,
        source = sources.Rare,
        rareName = L["Emberdusk"],
    },
    {
        name = "Winding Slitherdrake: Large Spiked Nose",
        itemID = 203347,
        questID = 73838,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 16,
    },
    --{
    --    name = "Winding Slitherdrake: Light Blue and Copper Armor",
    --    itemID = 203301,
    --    questID = 73789,
    --},
    {
        name = "Winding Slitherdrake: Long Chin Horn",
        itemID = 203309,
        questID = 73797,
        source = sources.Rare,
        rareName = L["Goopal"],
    },
    {
        name = "Winding Slitherdrake: Long Jaw Horns",
        itemID = 203341,
        questID = 73832,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 13,
    },
    {
        name = "Winding Slitherdrake: Plated Brow",
        itemID = 203307,
        questID = 73795,
        source = sources.Rare,
        rareName = L["Alcanon"],
    },
    {
        name = "Winding Slitherdrake: Pointed Nose",
        itemID = 203348,
        questID = 73839,
        source = sources.DragonRacingContainer,
        containerID = 205226,
    },
    --{
    --    name = "Winding Slitherdrake: Purple and Silver Armor",
    --    itemID = 203302,
    --    questID = 73790,
    --},
    {
        name = "Winding Slitherdrake: Red and Gold Armor",
        itemID = 203303,
        questID = 73791,
        source = sources.DragonRacingAchievement,
        achievementID = 17487,
    },
    {
        name = "Winding Slitherdrake: Red Hair",
        itemID = 203325,
        questID = 73813,
        source = sources.DragonRacingAchievement,
        achievementID = 17484,
    },
    {
        name = "Winding Slitherdrake: Red Scales",
        itemID = 203353,
        questID = 73844,
        source = sources.Renown,
        renownFaction = 2507,
        renownRank = "22",
    },
    {
        name = "Winding Slitherdrake: Tan Horns",
        itemID = 203327,
        questID = 73815,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 5,
    },
    {
        name = "Winding Slitherdrake: Triple Jaw Horns",
        itemID = 203342,
        questID = 73833,
        source = sources.DragonRacingContainer,
        containerID = 205226,
    },
    {
        name = "Winding Slitherdrake: Small Finned Crest",
        itemID = 203317,
        questID = 73805,
        source = sources.DragonRacingContainer,
        containerID = 205226,
    },
    {
        name = "Winding Slitherdrake: Small Finned Tail",
        itemID = 203358,
        questID = 73850,
        source = sources.Rare,
        rareName = L["Karokta"],
    },
    {
        name = "Winding Slitherdrake: Small Finned Throat",
        itemID = 203364,
        questID = 73856,
        source = sources.Inscription,
    },
    {
        name = "Winding Slitherdrake: Spiked Chin",
        itemID = 203313,
        questID = 73801,
        source = sources.Chest,
        chestName = L["Smelly Trash Pile"],
    },
    {
        name = "Winding Slitherdrake: Split Jaw Horns",
        itemID = 203345,
        questID = 73836,
        source = sources.Rare,
        rareName = L["Viridian King"],
    },
    {
        name = "Winding Slitherdrake: Swept Horns",
        itemID = 203330,
        questID = 73818,
        source = sources.Quest,
        sourceQuestID = 74562,
    },
    {
        name = "Winding Slitherdrake: White Hair",
        itemID = 203324,
        questID = 73812,
        source = sources.Inscription,
    },
    {
        name = "Winding Slitherdrake: White Horns",
        itemID = 203328,
        questID = 73816,
        source = sources.Rare,
        rareName = L["Invoq"],
    },
    {
        name = "Winding Slitherdrake: Yellow and Silver Armor",
        itemID = 203304,
        questID = 73792,
        source = sources.Inscription,
    },
}

for k, v in pairs(manuscripts) do
    v.category = addon.Enum.Drakes.WindingSlitherdrake
    table.insert(addon.db, v)
end
